version: '3.8'

services:
  db:
    build: ./database/Dockerfile
    ports:
      - "3306:3306"
  backend:
    build: ./backend/Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      - database
    environment:
      - BASE_URL_PORT=5000
      - MYSQL_ROOT_PASSWORD=s3k0l4hd3v0p5
      - DATABASE_USERNAME=people
      - DATABASE_PASSWORD=people
      - DATABASE_DATABASE=people
      - DATABASE_HOST=db
      - DATABASE_PORT=3306
